baseURL = "https://qbart.dev/"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Bartłomiej Wójtowicz"
theme = "custom"
enableEmoji = true
disqusShortname = "qbart"
GoogleAnalytics = "UA-143750284-1"
footnotereturnlinkcontents = "↩"
pygmentsCodeFences = true
pygmentsStyle="dracula"
copyright="Bartłomiej Wójtowicz"
rssLimit=20

[author]
name = "Bartłomiej Wójtowicz"

[taxonomies]
#tag = "tags"

[permalinks]
posts = "/:section/:year/:slug"


[Params]
# seo
description = "Engineering blog of Bartłomiej Wójtowicz. CTO at Selleo Labs. Co-founder of Soft Kiwi Games."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false
readTime = true

# Intro on main page, content is markdown
homeIntroTitle = 'Hello there!'
homeIntroContent = """
My name is Bartłomiej Wójtowicz, currently the CTO at [Selleo Labs](https://selleo.com?utm_source=qbart.dev&utm_campaign=qbart.dev),
where we support our clients with business and product development.
As an engineer I am always eager to grow and build new things.
In my free time I learn how to play piano, hone my so-so drawing skills and enjoy good board games and squash.
Animation enthusiast in every form.
While I occasionally play video games, I'm mostly interested in the magic behind - rendering, game design, AI, physics and math.
Together with my cousin, we run a small indie game development studio called [Soft Kiwi Games](https://softkiwi.games),
where we bring our passion for gaming to life.
"""

footerContent = "\"The more I learn, the more I realize how much I don't know.\""

paginationSize = 100
listSummaries = false
listDateFormat = 'Jan 2006'

breadcrumbs = false
math = true
autonumber = false
toc = true

followLink = "https://www.linkedin.com/in/bart%C5%82omiej-w%C3%B3jtowicz/"

[[Params.Social]]
name = "mail"
url = "mailto:hi@qbart.dev?subject=Business inquiry"
svg = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>'

[[Params.Social]]
name = "github"
url = "https://github.com/qbart"
svg = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>'

[[Params.Social]]
name = "pinterest"
url = "https://pinterest.com/bartlomiejwojtowicz/"
svg='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12.035 1.998c-5.089 0-8.225 3.62-8.225 7.454 0 1.813 1.01 4.073 2.626 4.794.246.112.377.062.434-.164.041-.171.262-1.004.363-1.395a.378.378 0 0 0-.092-.378c-.537-.644-.974-1.83-.974-2.942 0-2.849 2.165-5.605 5.864-5.605 3.2 0 5.456 2.18 5.456 5.29 0 3.572-1.88 6.043-4.322 6.043-1.35 0-2.36-1.114-2.035-2.48.388-1.635 1.139-3.396 1.139-4.571 0-1.054-.566-1.932-1.736-1.932-1.377 0-2.486 1.424-2.486 3.331 0 1.216.409 2.038.409 2.038s-1.402 5.94-1.648 6.982c-.49 2.094-.074 4.665-.038 4.916.02.148.211.184.3.072.124-.154 1.736-2.151 2.283-4.143.155-.566.876-3.49.876-3.49.433.826 1.7 1.554 3.048 1.554 4.009 0 6.93-3.493 6.93-7.851 0-3.397-2.878-6.588-7.067-6.588Z"/></svg>'

[[Params.Social]]
name = "x"
url = "https://x.com/softkiwi"
svg = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>'

[[Params.Social]]
name = "youtube"
url = "https://www.youtube.com/@SoftKiwiGames"
svg = '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M23.5 6.186a2.994 2.994 0 0 0-2.105-2.12C19.5 3.5 12 3.5 12 3.5s-7.5 0-9.395.566A2.994 2.994 0 0 0 .5 6.186 31.64 31.64 0 0 0 0 12a31.64 31.64 0 0 0 .5 5.814 2.994 2.994 0 0 0 2.105 2.12C4.5 20.5 12 20.5 12 20.5s7.5 0 9.395-.566a2.994 2.994 0 0 0 2.105-2.12A31.64 31.64 0 0 0 24 12a31.64 31.64 0 0 0-.5-5.814ZM9.75 15.5v-7l6.25 3.5-6.25 3.5Z"/></svg>'

[[Params.Social]]
name = "facebook"
url = "https://www.facebook.com/softkiwigames"
svg = '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M22 12.07C22 6.48 17.52 2 11.93 2 6.35 2 1.87 6.48 1.87 12.07c0 4.87 3.43 8.93 7.92 9.87v-6.98H7.9v-2.89h1.9v-2.2c0-1.87 1.11-2.9 2.8-2.9.81 0 1.66.15 1.66.15v1.83h-.94c-.93 0-1.22.58-1.22 1.18v1.94h2.08l-.33 2.89h-1.75v6.98c4.49-.94 7.92-5 7.92-9.87Z"/></svg>'


[markup]
[markup.highlight]
style = 'algol'

